// <auto-generated />
using ECommerce_WebApp.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce_WebApp.Services.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241126225530_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ECommerce_WebApp.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Computers & Accessories",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Smartphones",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Home Appliances"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Kitchen Appliances",
                            ParentCategoryId = 4
                        });
                });

            modelBuilder.Entity("ECommerce_WebApp.Entities.Product", b =>
                {
                    b.Property<int>("ProdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProdDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProdPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ProdRating")
                        .HasColumnType("TEXT");

                    b.HasKey("ProdId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProdId = 5,
                            CategoryId = 1,
                            ProdDescription = "Large-screen TV with 4K resolution for ultimate entertainment.",
                            ProdImage = "4k_tv.jpg",
                            ProdName = "4K Ultra HD TV",
                            ProdPrice = 799.99m,
                            ProdRating = 4.6m
                        },
                        new
                        {
                            ProdId = 6,
                            CategoryId = 1,
                            ProdDescription = "Wireless headphones with noise cancellation and high-fidelity sound.",
                            ProdImage = "bluetooth_headphones.jpg",
                            ProdName = "Bluetooth Headphones",
                            ProdPrice = 199.99m,
                            ProdRating = 4.3m
                        },
                        new
                        {
                            ProdId = 7,
                            CategoryId = 2,
                            ProdDescription = "RGB backlit mechanical keyboard for gaming and productivity.",
                            ProdImage = "mechanical_keyboard.jpg",
                            ProdName = "Mechanical Keyboard",
                            ProdPrice = 89.99m,
                            ProdRating = 4.7m
                        },
                        new
                        {
                            ProdId = 8,
                            CategoryId = 2,
                            ProdDescription = "2TB portable external hard drive for data backup and storage.",
                            ProdImage = "external_hard_drive.jpg",
                            ProdName = "External Hard Drive",
                            ProdPrice = 59.99m,
                            ProdRating = 4.4m
                        },
                        new
                        {
                            ProdId = 9,
                            CategoryId = 3,
                            ProdDescription = "Budget smartphone with excellent performance and camera quality.",
                            ProdImage = "smartphone_abc.jpg",
                            ProdName = "Smartphone ABC",
                            ProdPrice = 299.99m,
                            ProdRating = 4.1m
                        },
                        new
                        {
                            ProdId = 10,
                            CategoryId = 3,
                            ProdDescription = "Includes phone case, screen protector, and charging cable.",
                            ProdImage = "smartphone_accessories.jpg",
                            ProdName = "Smartphone Accessories Pack",
                            ProdPrice = 49.99m,
                            ProdRating = 4.0m
                        },
                        new
                        {
                            ProdId = 11,
                            CategoryId = 4,
                            ProdDescription = "Compact microwave with multiple cooking modes.",
                            ProdImage = "microwave_oven.jpg",
                            ProdName = "Microwave Oven",
                            ProdPrice = 129.99m,
                            ProdRating = 4.5m
                        },
                        new
                        {
                            ProdId = 12,
                            CategoryId = 4,
                            ProdDescription = "HEPA air purifier for clean and fresh indoor air.",
                            ProdImage = "air_purifier.jpg",
                            ProdName = "Air Purifier",
                            ProdPrice = 149.99m,
                            ProdRating = 4.6m
                        },
                        new
                        {
                            ProdId = 13,
                            CategoryId = 5,
                            ProdDescription = "Two-slice toaster with adjustable browning levels.",
                            ProdImage = "toaster.jpg",
                            ProdName = "Toaster",
                            ProdPrice = 24.99m,
                            ProdRating = 4.2m
                        },
                        new
                        {
                            ProdId = 14,
                            CategoryId = 5,
                            ProdDescription = "Automatic coffee maker with programmable brewing.",
                            ProdImage = "coffee_maker.jpg",
                            ProdName = "Coffee Maker",
                            ProdPrice = 79.99m,
                            ProdRating = 4.4m
                        },
                        new
                        {
                            ProdId = 15,
                            CategoryId = 1,
                            ProdDescription = "Control your smart home devices with a single hub.",
                            ProdImage = "smart_home_hub.jpg",
                            ProdName = "Smart Home Hub",
                            ProdPrice = 99.99m,
                            ProdRating = 4.3m
                        },
                        new
                        {
                            ProdId = 16,
                            CategoryId = 2,
                            ProdDescription = "Ergonomic gaming chair with adjustable height and lumbar support.",
                            ProdImage = "gaming_chair.jpg",
                            ProdName = "Gaming Chair",
                            ProdPrice = 199.99m,
                            ProdRating = 4.5m
                        });
                });

            modelBuilder.Entity("ECommerce_WebApp.Entities.Category", b =>
                {
                    b.HasOne("ECommerce_WebApp.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("ECommerce_WebApp.Entities.Product", b =>
                {
                    b.HasOne("ECommerce_WebApp.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce_WebApp.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
